version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "npm install && npm run start:dev"
    volumes:
      - ./:/app/
    ports:
      - '3000:3000'
    depends_on:
      - postgres

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
